# Generated by Django 6.0.3 on 2026-04-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('size_type', models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('numeric', 'Numeric')], default='clothing', max_length=20)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.product')),
            ],
            options={
                'ordering': ['order', 'label'],
                'unique_together': {('product', 'label')},
            },
        ),
    ]
