# Generated by Django 6.0.5 on 2026-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sync_in_stock_with_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='stock_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
