# Generated by Django 6.0.5 on 2026-05-29 17:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_stock_to_color_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
