# Generated by Django 6.0.3 on 2026-04-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_returnrequest_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_variant',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
