# Generated by Django 6.0.3 on 2026-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_size_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('pod', 'Pay on Delivery'), ('manual_transfer', 'Direct Bank Transfer')], default='card', max_length=20),
        ),
    ]
