# Generated by Django 6.0.3 on 2026-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_manual_transfer_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_notified',
            field=models.BooleanField(default=False),
        ),
    ]
