# Generated by Django 6.0.5 on 2026-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_transfer_notified_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card Payment'), ('transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('pod', 'Pay on Delivery'), ('manual_transfer', 'Direct Bank Transfer'), ('pickup', 'Self Pickup')], default='card', max_length=20),
        ),
    ]
